### ISSUE TITLE
generate-config.py does not work

### ISSUE THREAD

**Issue by bstarynk** [bstarynk/helpcovid#4]
commit 6cba80bbeebb560843a62aed5
```

rimski.x86_64 ~/helpcovid 9:48 .0 % ./generate-config.py 
Starting HelpCovid configuration generator...
See https://github.com/bstarynk/helpcovid and its README.md


 ==== HelpCovid web configuration =====

Enter web served URL, e.g. http://localhost:8089/ or https://example.com/

url: http://localhost:8089/
[url = http://localhost:8089/]
Enter web document root, a local directory containing web served resources (e.g. HTML files, CSS stylesheets)

root: /home/basile/helpcovid/webroot
[root = /home/basile/helpcovid/webroot]
Enter the OpenSSL public certificate, for HTTPS - can be left empty; see https://www.openssl.org/

sslcert: 
[sslcert = ]
Enter the OpenSSL private key, for HTTPS
sskey: 
[sskey = ]

 ==== HelpCovid PostGreSQL database configuration, see https://www.postgresql.org/ ====

Enter the PostGreSQL connnection string, see https://www.postgresql.org/docs/current/libpq-connect.html
connection: host=localhost port=5432 dbname=helpcovid_db
[connection = host=localhost port=5432 dbname=helpcovid_db]
Enter the HelpCovid PostgreSQL password file
passfile: /home/basile/helpcovid_dbpasswd
[passfile = /home/basile/helpcovid_dbpasswd]

Configuration file saved to /home/basile/.helpcovidrc]
Traceback (most recent call last):
  File "./generate-config.py", line 199, in <module>
    main()
  File "./generate-config.py", line 191, in main
    write_connection_keys(conn)
  File "./generate-config.py", line 117, in write_connection_keys
    config_dict['user'] = split[1]
IndexError: list index out of range
```

**Comment by achakravarti** [comment]
I understand the issue. The connection string is being expected in the format `database:user:password`, and so is not able to parse `host=localhost port=5432 dbname=helpcovid_db`

**Comment by bstarynk** [comment]
Then the prompt should give an example

**Comment by achakravarti** [comment]
With other rectificiations, works as follows:

```
[abhishek@archlinux helpcovid]$ ./generate-config
bash: ./generate-config: No such file or directory
[abhishek@archlinux helpcovid]$ ./generate-config.py
Starting HelpCovid configuration generator...
See https://github.com/bstarynk/helpcovid and its README.md


 ==== HelpCovid web configuration =====

Enter web served URL, e.g. http://localhost:8089/ or https://example.com/

url: localhost
[url = localhost]
Enter web document root, a local directory containing web served resources (e.g. HTML files, CSS stylesheets)

root: webroot
[root = webroot]
Enter the OpenSSL public certificate, for HTTPS - can be left empty; see https://www.openssl.org/

sslcert: 
[sslcert = ]
Enter the OpenSSL private key, for HTTPS
sskey: 
[sskey = ]

 ==== HelpCovid PostGreSQL database configuration, see https://www.postgresql.org/ ====

Enter the PostGreSQL connnection string, see https://www.postgresql.org/docs/current/libpq-connect.html
The format is dbname:username:password
connection: helpcovid_db:helpcovid_usr:passwd12345helpcovid
[connection = helpcovid_db:helpcovid_usr:passwd12345helpcovid]
Enter *full path* of the HelpCovid PostgreSQL password file
passfile: /home/abhishek/.helpcovid_pgpasswd
[passfile = /home/abhishek/.helpcovid_pgpasswd]

Configuration file saved to /home/abhishek/.helpcovidrc]
Creating database...
could not change directory to "/home/abhishek/work/bstarynk/helpcovid": Permission denied
psql:/tmp/tmp3zsh4qschelpcovid:8: NOTICE:  user already exists; skipping...
DO
ALTER ROLE
ALTER ROLE
ALTER ROLE
GRANT
removed '/tmp/tmp3zsh4qschelpcovid'
Password file created at /home/abhishek/.helpcovid_pgpasswd
[abhishek@archlinux helpcovid]$ 
```

**Comment by bstarynk** [comment]
Should work in commit f3212cfe1af088adf7d2f126436
